<a href="https://colab.research.google.com/github/hameedk1/DSML_Task7/blob/main/DSML__Task7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy

##1. How to extract all odd numbers from arr?


In [ ]:
import numpy as np
# Example list
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Extract odd numbers
odd_numbers = [num for num in arr if num % 2 != 0]

# Print the result
print(odd_numbers)


[1, 3, 5, 7, 9]


##2. Replace all odd numbers in arr with -1 without changing

In [ ]:
import numpy as np
# Example list
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Replace odd numbers with -1
new_arr = [-1 if num % 2 != 0 else num for num in arr]

# Print the result
print(new_arr)

[-1, 2, -1, 4, -1, 6, -1, 8, -1, 10]


##3.  Convert a 1D array to a 2D array with 2 rows



In [ ]:
import numpy as np


# Example 1D array
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Convert 1D array to 2D array with 2 rows
arr_2d = arr_1d.reshape(2, -1)

# Print the result
print(arr_2d)

[[1 2 3]
 [4 5 6]]


##4. Stack arrays a and b vertically



In [ ]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

#Desired Output:

#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

##5. Stack the arrays a and b horizontally.



In [ ]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

#Desired Output:

#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

##6.How to get the common items between two python numpy arrays?
Get the common items between a and b




In [ ]:
import numpy as np
# Example arrays
a = np.array([1,2,3])
b = np.array([4,5,6])
# Stack arrays vertically
stacked_array = np.vstack((a,b))
# Print the result
print(stacked_array)

[[1 2 3]
 [4 5 6]]


##7.How to remove from one array those items that exist in another?
Q. From array a remove all items present in array b

In [ ]:
import numpy as np

# Example arrays
array1 = np.array([1, 2, 3, 4, 5, 6])
array2 = np.array([2, 4, 6])
# Remove items from array1 that exist in array2
result_array = np.setdiff1d(array1,array2)
# Print the result
print(result_array)

[1 3 5]


##8. How to get the positions where elements of two arrays match?

Q. Get the positions where elements of a and b match



In [ ]:
import numpy as np
# Example arrays
array1 = np.array([1, 2, 3, 4, 5, 6])
array2 = np.array([1, 0, 3, 8, 5, 6])
# Find the positions where elements match
matching_positions = np.where(array1 == array2)[0]
# Print the matching positions
print(matching_positions)

[0 2 4 5]


##9. How to extract all numbers between a given range from a numpy array?
Get all items between 5 and 10 from a

In [ ]:
import numpy as np

# Example array
array = np.array([1, 3, 5, 7, 9, 11, 13, 15, 17, 19])
# Define the range
lower_bound = 5
upper_bound = 15
# Extract numbers within the range [lower_bound, upper_bound]
numbers_in_range = array[(array >= lower_bound) & (array <= upper_bound)]
# Print the result
print(numbers_in_range)

[ 5  7  9 11 13 15]


#Pandas

##Pandas Data Series

##1. Write a Pandas program to convert a dictionary to a Pandas series.

```
Sample Series:
Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}

Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64

```

In [ ]:
import pandas as pd

# Define the dictionary
data = {'a': 10, 'b': 20, 'c': 30, 'd': 40}
# Convert the dictionary to a Pandas series
series = pd.Series(data)
# Print the result
print(series)

a    10
b    20
c    30
d    40
dtype: int64


##2. Write a Pandas program to convert a NumPy array to a Pandas series.
```
Sample Series:
  NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

```

In [ ]:
import numpy as np
import pandas as pd

# Define the NumPy array
array = np.array([10, 20, 30, 40, 50])
# Convert the NumPy array to a Pandas series
series = pd.Series(array)
# Print the result
print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64


##3. Write a Pandas program to change the data type of given a column or a Series.

```
Sample Series:
    Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

```

In [ ]:
import pandas as pd

# Create a Series
s = pd.Series(['1', '2', '3', '4'])
# Convert the Series to integer
s = s.astype(int)
# Print the Series and its data type
print("Series after type conversion:")
print(s)
print("\nData type after conversion:")
print(s.dtypes)

Series after type conversion:
0    1
1    2
2    3
3    4
dtype: int64

Data type after conversion:
int64


##4. Write a Pandas program to convert the first column of a DataFrame as a Series.

```
Sample Output:  
Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

1st column as a Series:
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>

```

In [ ]:
import pandas as pd

# Create a DataFrame
d = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1, 11]}
df = pd.DataFrame(data=d)

print("Original DataFrame")
print(df)
# Convert the first column to a Series using iloc
s1 = df.iloc[:,0]
print("\n1st column as a Series")
print(s1)

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

1st column as a Series
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64


##5. Write a Pandas program to convert a given Series to an array.

```
Sample Output:
Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']
<class 'numpy.ndarray'>

```

In [2]:
import pandas as pd
import numpy as np
# Sample data for demonstration
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
# Convert Series to NumPy array using to_numpy()
array = series.to_numpy()
print("Original Series:")
print(series)
print("\nConverted to NumPy array:")
print(array)

Original Series:
0    1
1    2
2    3
3    4
4    5
dtype: int64

Converted to NumPy array:
[1 2 3 4 5]


##6 Write a Pandas program to convert Series of lists to one Series.
```
Sample Output:
Original Series of list
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object
One Series
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object

```

In [3]:
import pandas as pd

# Sample data for demonstration
data =pd.Series([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Series of lists:")
print(data)
# Convert Series of lists to one Series using explode
result = data.explode().reset_index(drop=True)
print("\nConverted to one Series:")
print(result)


Original Series of lists:
0    [1, 2, 3]
1    [4, 5, 6]
2    [7, 8, 9]
dtype: object

Converted to one Series:
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: object


In [ ]:
import pandas as pd

ps=pd.Series([['Red', 'Green', 'White'],['Red', 'Black'],['Yellow']])
ps.explode().reset_index(drop=True)

index       0
0      0     Red
1      0   Green
2      0   White
3      1     Red
4      1   Black
5      2  Yellow

##7.Write a Pandas program to sort a given Series.
```
Sample Output:
Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
0       100
1       200
3    300.12
4       400
2    python
dtype: object
```

In [4]:
import pandas as pd

# Sample data for demonstration
data = pd.Series([5, 3, 8, 6, 1, 9, 2, 7, 4])
print("Original Series:")
print(data)
# Sort the Series in ascending order
sorted_series_asc = data.sort_values(ascending = False)
print("\nSeries sorted in ascending order:")
print(sorted_series_asc)
# Sort the Series in descending order
sorted_series_desc = data.sort_values(ascending=False)

print("\nSeries sorted in descending order:")
print(sorted_series_desc)


Original Series:
0    5
1    3
2    8
3    6
4    1
5    9
6    2
7    7
8    4
dtype: int64

Series sorted in ascending order:
5    9
2    8
7    7
3    6
0    5
8    4
1    3
6    2
4    1
dtype: int64

Series sorted in descending order:
5    9
2    8
7    7
3    6
0    5
8    4
1    3
6    2
4    1
dtype: int64


##Pandas DataFrame

##1.Write a Pandas program to create a dataframe from a dictionary and display it.
```
Sample data: {'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}
Expected Output:
    X   Y   Z                                                         
0  78  84  86                                                        
1  85  94  97                                                         
2  96  89  96                                                      
3  80  83  72                                                         
4  86  86  83

```


In [5]:
import pandas as pd

# Define a dictionary with some sample data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [24, 27, 22, 32, 29],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'Salary': [70000, 80000, 65000, 90000, 75000]
}
# Create a DataFrame from the dictionary
df = pd.DataFrame(data)
# Display the DataFrame
print("DataFrame created from dictionary:")
print(df)

DataFrame created from dictionary:
      Name  Age         City  Salary
0    Alice   24     New York   70000
1      Bob   27  Los Angeles   80000
2  Charlie   22      Chicago   65000
3    David   32      Houston   90000
4      Eva   29      Phoenix   75000


##2. Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.
```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

```
Expected Output:
   attempts       name qualify  score                              
a         1  Anastasia     yes   12.5                                 
b         3       Dima      no    9.0                                 
....                              
i         2      Kevin      no    8.0                                
j         1      Jonas     yes   19.0

```

In [6]:
import pandas as pd

# Define a dictionary with some sample data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [24, 27, 22, 32, 29],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'Salary': [70000, 80000, 65000, 90000, 75000]
}
# Define custom index labels
index_labels = ['a', 'b', 'c', 'd', 'e']
# Create a DataFrame from the dictionary with custom index label
df = pd.DataFrame(data, index = index_labels)
# Display the DataFrame
print("DataFrame created from dictionary with custom index labels:")
print(df)

DataFrame created from dictionary with custom index labels:
      Name  Age         City  Salary
a    Alice   24     New York   70000
b      Bob   27  Los Angeles   80000
c  Charlie   22      Chicago   65000
d    David   32      Houston   90000
e      Eva   29      Phoenix   75000


##3. Write a Pandas program to get the first 3 rows of a given DataFrame.
```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

```
Expected Output:
First three rows of the data frame:                                   
   attempts       name qualify  score                              
a         1  Anastasia     yes   12.5                                 
b         3       Dima      no    9.0                                 
c         2  Katherine     yes   16.5

```

In [7]:
import pandas as pd

# Define a dictionary with some sample data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [24, 27, 22, 32, 29],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'Salary': [70000, 80000, 65000, 90000, 75000]
}
# Create a DataFrame from the dictionary
df = pd.DataFrame(data)
# Get the first 3 rows of the DataFrame
first_3_rows = df.head(3)
# Display the first 3 rows
print("First 3 rows of the DataFrame:")
print(first_3_rows)


First 3 rows of the DataFrame:
      Name  Age         City  Salary
0    Alice   24     New York   70000
1      Bob   27  Los Angeles   80000
2  Charlie   22      Chicago   65000


##4.Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Select specific columns:                                               
        name  score                                                  
a  Anastasia   12.5                                                   
b       Dima    9.0                                                
c  Katherine   16.5                                                    
...                                                  
h      Laura    NaN                                                   
i      Kevin    8.0                                                  
j      Jonas   19.0
```

In [8]:
import pandas as pd

# Define a dictionary with some sample data
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'score': [85, 90, 78, 88, 95],
    'age': [24, 27, 22, 32, 29],
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}
# Create a DataFrame from the dictionary
df = pd.DataFrame(data)
name_score_df =df[['name','score']]
# Display the selected columns
print("Selected 'name' and 'score' columns:")
print(name_score_df)

Selected 'name' and 'score' columns:
      name  score
0    Alice     85
1      Bob     90
2  Charlie     78
3    David     88
4      Eva     95


##5.  Write a Pandas program to select the specified columns and rows from a given data frame.
```
Sample Python dictionary data and list labels:
Select 'name' and 'score' columns in rows 1, 3, 5, 6 from the following data frame.
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Select specific columns and rows:
   score qualify
b    9.0      no
d    NaN      no
f   20.0     yes
g   14.5     yes

```

In [9]:

import pandas as pd

# Define a dictionary with some sample data
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'score': [85, 90, 78, 88, 95],
    'age': [24, 27, 22, 32, 29],
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)
# Select specific columns and rows using .loc[]
# Here we select rows with index 1, 2, and 3, and columns 'name' and 'score'
selected_data_loc = df.loc[1:3,['name', 'score']]
# Select specific columns and rows using .iloc[]
# Here we select rows by their position 1, 2, and 3, and columns by their position 0 (name) and 1 (score)
selected_data_iloc = df.iloc[1:4, [0, 1]]
# Display the selected data using .loc[]
print("Selected data using .loc[]:")
print(selected_data_loc)

# Display the selected data using .iloc[]
print("\nSelected data using .iloc[]:")
print(selected_data_iloc)

Selected data using .loc[]:
      name  score
1      Bob     90
2  Charlie     78
3    David     88

Selected data using .iloc[]:
      name  score
1      Bob     90
2  Charlie     78
3    David     88


##6. Write a Pandas program to select the rows where the number of attempts in the examination is greater than 2.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

```
Expected Output:
Number of attempts in the examination is greater than 2:
      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

```

In [10]:
import pandas as pd

# Define a dictionary with some sample data
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'score': [85, 90, 78, 88, 95],
    'attempts': [1, 3, 2, 3, 1],
    'age': [24, 27, 22, 32, 29]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)
# Filter rows where the number of attempts is greater than 2
filtered_df = df[df['attempts'] > 2]
# Display the filtered DataFrame
print("Rows where the number of attempts is greater than 2:")
print(filtered_df)

Rows where the number of attempts is greater than 2:
    name  score  attempts  age
1    Bob     90         3   27
3  David     88         3   32


##7. Write a Pandas program to select the rows where the score is missing, i.e. is NaN.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

```
Expected Output:
Rows where score is missing:
   attempts   name qualify  score
d         3  James      no    NaN
h         1  Laura      no    NaN

```

In [12]:
import pandas as pd
import numpy as np

# Define a dictionary with some sample data including NaN values
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'score': [85, np.nan, 78, np.nan, 95],
    'attempts': [1, 3, 2, 3, 1],
    'age': [24, 27, 22, 32, 29]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Filter rows where the 'score' column is NaN
filtered_df = df[df['score'].isna()]

# Display the filtered DataFrame
print("Rows where the 'score' is NaN:")
print(filtered_df)

Rows where the 'score' is NaN:
    name  score  attempts  age
1    Bob    NaN         3   27
3  David    NaN         3   32


##8. Write a Pandas program to select the rows the score is between 15 and 20 (inclusive).
```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Rows where score between 15 and 20 (inclusive):                        
   attempts       name qualify  score                                  
c         2  Katherine     yes   16.5                                
f         3    Michael     yes   20.0                                 
j         1      Jonas     yes   19.0
```


In [13]:
import pandas as pd

# Define a dictionary with some sample data
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'score': [18, 90, 16, 88, 20],
    'attempts': [1, 3, 2, 3, 1],
    'age': [24, 27, 22, 32, 29]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)
filtered_df = df[(df['score'] >= 15) & (df['score'] <=20)]
# Display the filtered DataFrame
print("Rows where the 'score' is between 15 and 20 (inclusive):")
print(filtered_df)

Rows where the 'score' is between 15 and 20 (inclusive):
      name  score  attempts  age
0    Alice     18         1   24
2  Charlie     16         2   22
4      Eva     20         1   29


##9. Write a Pandas program to select the rows where number of attempts in the examination is less than 2 and score greater than 15.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Number of attempts in the examination is less than 2 and score greater than 15 :
    name  score  attempts qualify
j  Jonas   19.0         1     yes

```

In [1]:
import pandas as pd

# Define a dictionary with some sample data
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'score': [18, 12, 16, 8, 20],
    'attempts': [1, 3, 2, 1, 1],
    'age': [24, 27, 22, 32, 29]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Filter rows where number of attempts is less than 2 and score is greater than 15
filtered_df = df[(df['attempts'] < 2) & (df['score'] > 15)]

# Display the filtered DataFrame
print("Rows where number of attempts is less than 2 and score is greater than 15:")
print(filtered_df)

Rows where number of attempts is less than 2 and score is greater than 15:
    name  score  attempts  age
0  Alice     18         1   24
4    Eva     20         1   29


##10. Write a Pandas program to change the score in row 'd' to 11.5.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

```

```
Expected Output:
Change the score in row 'd' to 11.5:                                  
   attempts       name qualify  score                                
a         1  Anastasia     yes   12.5                               
b         3       Dima      no    9.0                                
c         2  Katherine     yes   16.5
...                                
i         2      Kevin      no    8.0                                 
j         1      Jonas     yes   19.0

```

In [2]:
import pandas as pd

# Define a dictionary with some sample data
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'score': [18, 12, 16, 8, 20],
    'attempts': [1, 3, 2, 1, 1],
    'age': [24, 27, 22, 32, 29]
}

# Create a DataFrame from the dictionary with custom row labels
df = pd.DataFrame(data, index=['a', 'b', 'c', 'd', 'e'])
# Update the score in row 'd' to 11.5
df.loc['d', 'score'] = 11.5

# Display the updated DataFrame
print("Updated DataFrame:")
print(df)

Updated DataFrame:
      name  score  attempts  age
a    Alice   18.0         1   24
b      Bob   12.0         3   27
c  Charlie   16.0         2   22
d    David   11.5         1   32
e      Eva   20.0         1   29


##11. Write a Pandas program to calculate the sum of the examination attempts by the students.
```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Sum of the examination attempts by the students:                     
19
```

In [3]:
import pandas as pd

# Define a dictionary with some sample data
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'score': [18, 12, 16, 8, 20],
    'attempts': [1, 3, 2, 1, 1],
    'age': [24, 27, 22, 32, 29]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)
# Calculate the sum of examination attempts
total_attempts = df['attempts'].sum()

# Display the result
print("Sum of the examination attempts by the students:", total_attempts)

Sum of the examination attempts by the students: 8


##12. Write a Pandas program to calculate the mean of all students' scores. Data is stored in a dataframe.
```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Mean score for each different student in data frame:                  
13.5625
```

##13. Write a Pandas program to replace the 'qualify' column contains the values 'yes' and 'no' with True and False.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

```
Expected Output:
Replace the 'qualify' column contains the values 'yes' and 'no'  with T
rue and  False:                                                      
   attempts       name  qualify  score                              
a         1  Anastasia     True   12.5                          
b         3       Dima    False    9.0                              
......                           
i         2      Kevin    False    8.0                                 
j         1      Jonas     True   19.0
```

In [4]:
import pandas as pd

# Define a dictionary with some sample data
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'score': [18, 12, 16, 8, 20],
    'attempts': [1, 3, 2, 1, 1],
    'age': [24, 27, 22, 32, 29]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Calculate the mean of students' scores
mean_score = df['score'].mean()

# Display the result
print("Mean of all students' scores:", mean_score)

Mean of all students' scores: 14.8


##14. Write a Pandas program to change the name 'James' to 'Suresh' in name column of the DataFrame.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Change the name 'James' to \?Suresh\?:                                
   attempts       name qualify  score                                  
a         1  Anastasia     yes   12.5                                  
b         3       Dima      no    9.0                                  
.......                               
i         2      Kevin      no    8.0                                 
j         1      Jonas     yes   19.0
```

In [5]:
import pandas as pd

# Define a dictionary with some sample data
data = {
    'name': ['Alice', 'Bob', 'James', 'David', 'Eva'],
    'score': [18, 12, 16, 8, 20],
    'attempts': [1, 3, 2, 1, 1],
    'age': [24, 27, 22, 32, 29]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Replace the name 'James' with 'Suresh'
df['name'] = df['name'].replace('James', 'Suresh')
# Display the updated DataFrame
print("Updated DataFrame:")
print(df)

Updated DataFrame:
     name  score  attempts  age
0   Alice     18         1   24
1     Bob     12         3   27
2  Suresh     16         2   22
3   David      8         1   32
4     Eva     20         1   29


##15. Write a Pandas program to delete the 'attempts' column from the DataFrame.
```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Delete the 'attempts' column from the data frame:                    
        name qualify  score                                          
a  Anastasia     yes   12.5                                           
b       Dima      no    9.0                                          
.....                                       
i      Kevin      no    8.0                                          
j      Jonas     yes   19.0
```

In [6]:
import pandas as pd

# Define a dictionary with some sample data
data = {
    'name': ['Alice', 'Bob', 'James', 'David', 'Eva'],
    'score': [18, 12, 16, 8, 20],
    'attempts': [1, 3, 2, 1, 1],
    'age': [24, 27, 22, 32, 29]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Delete the 'attempts' column
df = df.drop(columns=['attempts'])
# Display the updated DataFrame
print("Updated DataFrame:")
print(df)

Updated DataFrame:
    name  score  age
0  Alice     18   24
1    Bob     12   27
2  James     16   22
3  David      8   32
4    Eva     20   29


##16.  Write a Pandas program to insert a new column in existing DataFrame.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
New DataFrame after inserting the 'color' column                       
   attempts       name qualify  score   color                       
a         1  Anastasia     yes   12.5     Red                         
b         3       Dima      no    9.0    Blue                        
.......                     
i         2      Kevin      no    8.0   Green                        
j         1      Jonas     yes   19.0     Red
```

In [7]:
import pandas as pd

# Define a dictionary with some sample data
data = {
    'name': ['Alice', 'Bob', 'James', 'David', 'Eva'],
    'score': [18, 12, 16, 8, 20],
    'age': [24, 27, 22, 32, 29]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Insert a new column 'grade' with default values
df['grade'] = ['A', 'B', 'A', 'C', 'A']
# Display the updated DataFrame
print("Updated DataFrame:")
print(df)

Updated DataFrame:
    name  score  age grade
0  Alice     18   24     A
1    Bob     12   27     B
2  James     16   22     A
3  David      8   32     C
4    Eva     20   29     A


##17.  Write a Pandas program to rename columns of a given DataFrame

```
Sample data:
Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9
New DataFrame after renaming columns:
   Column1  Column2  Column3
0        1        4        7
1        2        5        8
2        3        6        9
```

In [8]:
import pandas as pd

# Define a dictionary with some sample data
data = {
    'name': ['Alice', 'Bob', 'James', 'David', 'Eva'],
    'score': [18, 12, 16, 8, 20],
    'age': [24, 27, 22, 32, 29]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Rename columns
df.rename(columns={'name': 'student_name', 'score': 'exam_score', 'age': 'student_age'}, inplace=True)
# Display the updated DataFrame
print("Updated DataFrame:")
print(df)


Updated DataFrame:
  student_name  exam_score  student_age
0        Alice          18           24
1          Bob          12           27
2        James          16           22
3        David           8           32
4          Eva          20           29


##18. Write a Pandas program to select rows from a given DataFrame based on values in some columns.
```
Sample data:
Original DataFrame
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
Rows for colum1 value == 4
   col1  col2  col3
1     4     5     8
3     4     7     0
```

In [9]:
import pandas as pd

# Define a dictionary with some sample data
data = {
    'name': ['Alice', 'Bob', 'James', 'David', 'Eva'],
    'score': [18, 12, 16, 8, 20],
    'age': [24, 27, 22, 32, 29]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Select rows where the score is greater than 15
selected_rows = df[df['score'] > 15]

# Display the selected rows
print("Selected Rows where score > 15:")
print(selected_rows)

Selected Rows where score > 15:
    name  score  age
0  Alice     18   24
2  James     16   22
4    Eva     20   29


##19. Write a Pandas program to add one row in an existing DataFrame.

```
Sample data:
Original DataFrame
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
After add one row:
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
5    10    11    12
```

In [10]:
import pandas as pd

# Define a dictionary with some sample data
data = {
    'name': ['Alice', 'Bob', 'James', 'David', 'Eva'],
    'score': [18, 12, 16, 8, 20],
    'age': [24, 27, 22, 32, 29]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Add a new row using loc method
df.loc[len(df)] = ['John', 15, 25]
# Display the updated DataFrame
print("Updated DataFrame using loc method:")
print(df)

Updated DataFrame using loc method:
    name  score  age
0  Alice     18   24
1    Bob     12   27
2  James     16   22
3  David      8   32
4    Eva     20   29
5   John     15   25


##20. Write a Pandas program to replace all the NaN values with Zero's in a column of a dataframe.

```
Sample data:
Original DataFrame

   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
2         2  Katherine     yes   16.5
.....
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0

```
```

New DataFrame replacing all NaN with 0:
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
2         2  Katherine     yes   16.5
.....
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0
```

In [11]:
import pandas as pd
import numpy as np

# Define a dictionary with some sample data including NaN values
data = {
    'name': ['Alice', 'Bob', 'James', 'David', 'Eva'],
    'score': [18, np.nan, 16, np.nan, 20],
    'age': [24, 27, 22, 32, 29]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame:")
print(df)

# Replace NaN values with zeros in the 'score' column
df['score'] = df['score'].fillna(0)

# Display the updated DataFrame
print("\nDataFrame after replacing NaN values with zeros in the 'score' column:")
print(df)

Original DataFrame:
    name  score  age
0  Alice   18.0   24
1    Bob    NaN   27
2  James   16.0   22
3  David    NaN   32
4    Eva   20.0   29

DataFrame after replacing NaN values with zeros in the 'score' column:
    name  score  age
0  Alice   18.0   24
1    Bob    0.0   27
2  James   16.0   22
3  David    0.0   32
4    Eva   20.0   29


##21. Write a Pandas program to count the NaN values in one or more columns in DataFrame.
```
Sample data:
Original DataFrame
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
2         2  Katherine     yes   16.5
3         3      James      no    NaN
4         2      Emily      no    9.0
5         3    Michael     yes   20.0
6         1    Matthew     yes   14.5
7         1      Laura      no    NaN
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0

Number of NaN values in one or more columns:
2

```

In [12]:
import pandas as pd
import numpy as np

# Define a dictionary with some sample data including NaN values
data = {
    'name': ['Alice', 'Bob', 'James', 'David', 'Eva'],
    'score': [18, np.nan, 16, np.nan, 20],
    'age': [24, 27, np.nan, 32, 29]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame:")
print(df)

# Count NaN values in the 'score' and 'age' columns
nan_counts = df[['score', 'age']].isna().sum()
# Display the NaN counts
print("\nNaN counts in 'score' and 'age' columns:")
print(nan_counts)

Original DataFrame:
    name  score   age
0  Alice   18.0  24.0
1    Bob    NaN  27.0
2  James   16.0   NaN
3  David    NaN  32.0
4    Eva   20.0  29.0

NaN counts in 'score' and 'age' columns:
score    2
age      1
dtype: int64


##22. Write a Pandas program to drop a list of rows from a specified DataFrame.
```
Sample data:
Original DataFrame
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1


New DataFrame after removing 2nd & 4th rows:
   col1  col2  col3
0     1     4     7
1     4     5     8
3     4     7     0
```

In [13]:
import pandas as pd

# Define a dictionary with some sample data
data = {
    'name': ['Alice', 'Bob', 'James', 'David', 'Eva'],
    'score': [18, 12, 16, 8, 20],
    'age': [24, 27, 22, 32, 29]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame:")
print(df)

# Specify the indices of rows to drop
rows_to_drop = [1, 3]
# Drop the specified rows
df = df.drop(rows_to_drop)
# Display the updated DataFrame
print("\nDataFrame after dropping specified rows:")
print(df)

Original DataFrame:
    name  score  age
0  Alice     18   24
1    Bob     12   27
2  James     16   22
3  David      8   32
4    Eva     20   29

DataFrame after dropping specified rows:
    name  score  age
0  Alice     18   24
2  James     16   22
4    Eva     20   29


##23. . Write a Pandas program to convert DataFrame column type from string to datetime.

```

Sample data:
String Date:
0    3/11/2000
1    3/12/2000
2    3/13/2000
dtype: object


Original DataFrame (string to datetime):
           0
0 2000-03-11
1 2000-03-12
2 2000-03-13
```

In [14]:
import pandas as pd

# Define a dictionary with some sample data including date strings
data = {
    'date_strings': ['2022-01-01', '2023-05-15', '2024-12-31']
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame:")
print(df)

# Convert the 'date_strings' column to datetime
df['date_strings'] = pd.to_datetime(df['date_strings'])

# Display the updated DataFrame with datetime column
print("\nDataFrame after converting column type to datetime:")
print(df)

Original DataFrame:
  date_strings
0   2022-01-01
1   2023-05-15
2   2024-12-31

DataFrame after converting column type to datetime:
  date_strings
0   2022-01-01
1   2023-05-15
2   2024-12-31


##24. Write a Pandas program to find the row for where the value of a given column is maximum.

```
Sample Output:
Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6    12
3     4     9     1
4     7     5    11
Row where col1 has maximum value:
4
Row where col2 has maximum value:
3
Row where col3 has maximum value:
2
```

In [15]:
import pandas as pd

# Define a dictionary with some sample data
data = {
    'name': ['Alice', 'Bob', 'James', 'David', 'Eva'],
    'score': [18, 12, 16, 25, 20],
    'age': [24, 27, 22, 32, 29]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame:")
print(df)

# Find the row where the 'score' column has the maximum value
max_row = df[df['score'] == df['score'].max()]
# Display the row with the maximum value in the 'score' column
print("\nRow with maximum value in 'score' column:")
print(max_row)

Original DataFrame:
    name  score  age
0  Alice     18   24
1    Bob     12   27
2  James     16   22
3  David     25   32
4    Eva     20   29

Row with maximum value in 'score' column:
    name  score  age
3  David     25   32


##25. Write a Pandas program to get the datatypes of columns of a DataFrame.

```
Sample data:
Original DataFrame:
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
.......
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0
Data types of the columns of the said DataFrame:
attempts      int64
name         object
qualify      object
score       float64
dtype: object
```

In [16]:
import pandas as pd

# Define a dictionary with some sample data
data = {
    'name': ['Alice', 'Bob', 'James', 'David', 'Eva'],
    'score': [18, 12, 16, 25, 20],
    'age': [24, 27, 22, 32, 29]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame:")
print(df)

# Get the datatypes of columns in the DataFrame
column_types = df.dtypes

# Display the datatypes of columns
print("\nDatatypes of columns:")
print(column_types)

Original DataFrame:
    name  score  age
0  Alice     18   24
1    Bob     12   27
2  James     16   22
3  David     25   32
4    Eva     20   29

Datatypes of columns:
name     object
score     int64
age       int64
dtype: object


##26. Write a Pandas program to group by the first column and get second column as lists in rows.

```
Sample data:
Original DataFrame
col1 col2
0 C1 1
1 C1 2
2 C2 3
3 C2 3
4 C2 4
5 C3 6
6 C2 5


Group on the col1:
col1
C1 [1, 2]
C2 [3, 3, 4, 5]
C3 [6]
Name: col2, dtype: object
```

In [17]:
import pandas as pd

# Define a dictionary with some sample data
data = {
    'category': ['A', 'B', 'A', 'B', 'A'],
    'value': [10, 20, 30, 40, 50]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame:")
print(df)

# Group by the first column and get the second column as lists in rows
grouped_df = df.groupby('category')['value'].agg(list).reset_index()
# Display the result
print("\nGrouped DataFrame with second column as lists in rows:")
print(grouped_df)

Original DataFrame:
  category  value
0        A     10
1        B     20
2        A     30
3        B     40
4        A     50

Grouped DataFrame with second column as lists in rows:
  category         value
0        A  [10, 30, 50]
1        B      [20, 40]


##27  Write a Pandas program to count number of columns of a DataFrame.

```
Sample Output:
Original DataFrame
  col1 col2 col3
0  1    4   7
1  2    5   8
2  3    6   12
3  4    9   1
4  7    5   11

Number of columns:
3
```

In [18]:
import pandas as pd

# Create a DataFrame for demonstration
data = {
    'name': ['Alice', 'Bob', 'James'],
    'age': [25, 30, 28],
    'city': ['New York', 'Los Angeles', 'Chicago']
}

df = pd.DataFrame(data)

# Get the number of columns using the shape attribute
num_columns = df.shape[1]

# Print the number of columns
print("Number of columns in the DataFrame:", num_columns)

Number of columns in the DataFrame: 3


##28.  Write a Pandas program to get first n records of a DataFrame.

```
Sample Output:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
3 4 9 12
4 7 5 1
5 11 0 11

First 3 rows of the said DataFrame':
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
```


In [19]:
import pandas as pd

# Create a DataFrame for demonstration
data = {
    'name': ['Alice', 'Bob', 'James', 'David', 'Eva'],
    'age': [25, 30, 28, 35, 27],
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Miami']
}

df = pd.DataFrame(data)

# Get the first 3 records using the head method
first_n_records = df.head(3)

# Print the first n records
print("First 3 records of the DataFrame:")
print(first_n_records)

First 3 records of the DataFrame:
    name  age         city
0  Alice   25     New York
1    Bob   30  Los Angeles
2  James   28      Chicago


##29. Write a Pandas program to get last n records of a DataFrame.

```
Sample Output:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
3 4 9 12
4 7 5 1
5 11 0 11

Last 3 rows of the said DataFrame':
col1 col2 col3
3 4 9 12
4 7 5 1
5 11 0 11
```

In [20]:
import pandas as pd

# Create a DataFrame for demonstration
data = {
    'name': ['Alice', 'Bob', 'James', 'David', 'Eva'],
    'age': [25, 30, 28, 35, 27],
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Miami']
}

df = pd.DataFrame(data)

# Get the last 3 records using the tail method
last_n_records = df.tail(3)

# Print the last n records
print("Last 3 records of the DataFrame:")
print(last_n_records)

Last 3 records of the DataFrame:
    name  age     city
2  James   28  Chicago
3  David   35  Houston
4    Eva   27    Miami


##30.  Write a Pandas program to get topmost n records within each group of a DataFrame.

```
Sample Output:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
3 4 9 12
4 7 5 1
5 11 0 11

```
```
topmost n records within each group of a DataFrame:
col1 col2 col3
5 11 0 11
4 7 5 1
3 4 9 12
col1 col2 col3
3 4 9 12
2 3 6 8
1 2 5 5
4 7 5 1
col1 col2 col3
3 4 9 12
5 11 0 11
2 3 6 8
```

In [21]:
import pandas as pd

# Create a DataFrame for demonstration
data = {
    'group': ['A', 'A', 'B', 'B', 'B', 'A', 'B'],
    'value': [10, 20, 15, 25, 30, 12, 28]
}

df = pd.DataFrame(data)

# Define a function to get top n records within each group
def top_n_records(group, n):
    return group.nlargest(n, 'value')

# Get the top 2 records within each group using apply and lambda function
top_n_per_group = df.groupby('group').apply(lambda x: top_n_records(x, 2))

# Print the top n records within each group
print("Top 2 records within each group:")
print(top_n_per_group)

Top 2 records within each group:
        group  value
group               
A     1     A     20
      5     A     12
B     4     B     30
      6     B     28


##31. Write a Pandas program to add a prefix or suffix to all columns of a given DataFrame.

```
Sample Output:
Original DataFrame
W X Y Z
0 68 78 84 86
1 75 85 94 97
2 86 96 89 96
3 80 80 83 72
4 66 86 86 83

Add prefix:
A_W A_X A_Y A_Z
0 68 78 84 86
1 75 85 94 97
2 86 96 89 96
3 80 80 83 72
4 66 86 86 83

Add suffix:
W_1 X_1 Y_1 Z_1
0 68 78 84 86
1 75 85 94 97
2 86 96 89 96
3 80 80 83 72
4 66 86 86 83

```

In [22]:
import pandas as pd

# Create a DataFrame for demonstration
data = {
    'name': ['Alice', 'Bob', 'James'],
    'age': [25, 30, 28],
    'city': ['New York', 'Los Angeles', 'Chicago']
}

df = pd.DataFrame(data)

# Add a prefix to all columns
prefixed_df = df.add_prefix('prefix_')
# Add a suffix to all columns
suffixed_df = df.add_suffix('_suffix')

# Print the DataFrame with prefix
print("DataFrame with prefix:")
print(prefixed_df)

# Print the DataFrame with suffix
print("\nDataFrame with suffix:")
print(suffixed_df)

DataFrame with prefix:
  prefix_name  prefix_age  prefix_city
0       Alice          25     New York
1         Bob          30  Los Angeles
2       James          28      Chicago

DataFrame with suffix:
  name_suffix  age_suffix  city_suffix
0       Alice          25     New York
1         Bob          30  Los Angeles
2       James          28      Chicago


##32. Write a Pandas program to convert continuous values of a column in a given DataFrame to categorical.
```
Input:
{ 'Name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Syed Wharton'],
'Age': [18, 22, 40, 50, 80, 5] }


Output:
Age group:
0 kids
1 adult
2 elderly
3 adult
4 elderly
5 kids
Name: age_groups, dtype: category
Categories (3, object): [kids < adult < elderly]
```

In [23]:
import pandas as pd

# Create a DataFrame for demonstration
data = {
    'name': ['Alice', 'Bob', 'James', 'David', 'Eva'],
    'age': [25, 30, 28, 35, 27]
}

df = pd.DataFrame(data)

# Convert continuous values of 'age' column to categorical
df['age_category'] = pd.cut(df['age'], bins=[0, 25, 30, 40], labels=['Young', 'Mid', 'Old'])

# Print the DataFrame with age categories
print("DataFrame with age categories:")
print(df)

DataFrame with age categories:
    name  age age_category
0  Alice   25        Young
1    Bob   30          Mid
2  James   28          Mid
3  David   35          Old
4    Eva   27          Mid


##33. Write a Pandas program to append rows to an existing DataFrame and display the combined data.

```
Test Data:
tudent_data1
  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199


New Row(s)
student_id                  S6
name          Scarlette Fisher
marks                      205
dtype: object
```

In [26]:
import pandas as pd

# Create the original DataFrame
data = {
    'name': ['Alice', 'Bob', 'James'],
    'age': [25, 30, 28],
    'city': ['New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)

# Check if the DataFrame is not None
if df is not None:
    # Create new data to append
    new_data = {
        'name': ['Eva', 'Michael'],
        'age': [27, 32],
        'city': ['Miami', 'San Francisco']
    }
    df_to_append = pd.DataFrame(new_data)

    # Concatenate the original DataFrame with the new DataFrame
    combined_df = pd.concat([df, df_to_append], ignore_index=True)

    # Display the combined data
    print("Combined DataFrame:")
    print(combined_df)
else:
    print("Error: DataFrame is None")

Combined DataFrame:
      name  age           city
0    Alice   25       New York
1      Bob   30    Los Angeles
2    James   28        Chicago
3      Eva   27          Miami
4  Michael   32  San Francisco


##34  Write a Pandas program to join the two given dataframes along rows and merge with another dataframe along the common column id.

```
Test Data:
student_data1:
  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
student_data2:
  student_id              name  marks
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201
```
```

exam_data:
   student_id  exam_id
0          S1       23
1          S2       45
2          S3       12
3          S4       67
4          S5       21
5          S7       55
6          S8       33
7          S9       14
8         S10       56
9         S11       83
10        S12       88
11        S13       12
```


In [27]:
import pandas as pd

# Create the first DataFrame
data1 = {
    'id': [1, 2, 3],
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [25, 30, 35]
}
df1 = pd.DataFrame(data1)

# Create the second DataFrame
data2 = {
    'id': [4, 5, 6],
    'name': ['David', 'Eva', 'Frank'],
    'age': [40, 45, 50]
}
df2 = pd.DataFrame(data2)

# Join the two DataFrames along rows
joined_df = pd.concat([df1, df2], ignore_index=True)
# Create the third DataFrame to merge with the joined DataFrame
data3 = {
    'id': [1, 2, 3, 4, 5, 6],
    'score': [85, 90, 88, 92, 95, 91]
}
df3 = pd.DataFrame(data3)

# Merge the joined DataFrame with the third DataFrame along the common column 'id'
merged_df = pd.merge(joined_df, df3, on='id')
# Display the resulting DataFrame
print("Joined DataFrame:")
print(joined_df)
print("\nMerged DataFrame:")
print(merged_df)

Joined DataFrame:
   id     name  age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
3   4    David   40
4   5      Eva   45
5   6    Frank   50

Merged DataFrame:
   id     name  age  score
0   1    Alice   25     85
1   2      Bob   30     90
2   3  Charlie   35     88
3   4    David   40     92
4   5      Eva   45     95
5   6    Frank   50     91
